name: worflow-2
run-name: run workflow-2

on:
  workflow_run:
    workflows:
      - "workflow-1"
    types:
      - completed
jobs:
  job2:
    name: Multiply by 2
    runs-on: windows-latest
    needs: job1
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework_pre
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 2 > math-homework.txt
      - name: Upload math result of Job 2
        uses: actions/upload-artifact@v4
        with:
          name: homework_post
          path: math-homework.txt
          retention-days: 1
