name: workflow-1
run-name: ${{ github.actor }} is running math operations
on: [push]
jobs:
  job1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: expr 3 + 7 > math-homework.txt
      - name: Upload math result of Job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt
          retention-days: 1